#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_descriptor_heap : enable
#extension GL_EXT_buffer_reference : enable
#extension GL_EXT_nonuniform_qualifier : enable

layout(descriptor_heap, descriptor_stride = 1) uniform accelerationStructureEXT tlas[];
// layout(binding = 0, set = 0) uniform accelerationStructureEXT tlas;
layout(descriptor_heap, descriptor_stride = 1) uniform writeonly image2D image[];

// A payload structure to pass color data between shaders
layout(location = 0) rayPayloadEXT vec3 hitColor;

layout(buffer_reference) buffer RgenData {
   int tlasOffset;
   int imageOffset;
};

layout(push_constant) uniform PC {
   RgenData rgenData;
};

void ReadTlas(accelerationStructureEXT t) {
   // do nothing;
}

void main() {
   // Get the coordinates of the current pixel
   ivec2 pixelCoords = ivec2(gl_LaunchIDEXT.xy);
   vec2 dims = vec2(gl_LaunchSizeEXT.xy);

   // Normalize coordinates to a range from -1.0 to 1.0
   vec2 uv = (vec2(pixelCoords) + vec2(0.5)) / dims;
   vec2 d = uv * 2.0 - 1.0;

   // Set up a simple camera looking forward down the Z axis
   vec3 origin    = vec3(0.0, 0.0, -2.0);
   vec3 direction = normalize(vec3(d.x, d.y, 1.0));

   uint rayFlags = gl_RayFlagsOpaqueEXT;
   float tMin    = 0.001;
   float tMax    = 1000.0;

   // this doesnt terminate (program behaves the same if i put an infinite loop here instead)
   traceRayEXT(
      tlas[rgenData.tlasOffset],           // acceleration structure
      rayFlags,       // rayFlags
      0xFF,           // cullMask
      0,              // sbtRecordOffset
      0,              // sbtRecordStride
      0,              // missIndex
      origin,         // ray origin
      tMin,           // ray min range
      direction,      // ray direction
      tMax,           // ray max range
      0               // payload location index
   );

   // Write the color returned by the hit or miss shader to our image
   imageStore(image[rgenData.imageOffset], pixelCoords, vec4(hitColor, 1.0));
}
